[package]
name = "squalr-engine-api"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
squalr-engine-common = { path = "../squalr-engine-common" }
dashmap = ">=6.1.0"
log = ">=0.4.26"
num-traits = { version = ">=0.2.19" }
serde = { version = ">=1.0.139", features = ["derive"] }
serde_json = ">=1.0.139"
structopt = ">=0.3.26"
sysinfo = ">=0.31.2"

[build-dependencies]

