#![feature(profile-rustflags)]

[workspace]
members = [
    "squalr-engine",
    "squalr-engine-architecture",
    "squalr-engine-common",
    "squalr-engine-debuggers",
    "squalr-engine-memory",
    "squalr-engine-processes",
    "squalr-engine-projects",
    "squalr-engine-scanning",
    "squalr-engine-scripting",
    "squalr-gui",
    "squalr-android",
    "squalr-cli",
    "squalr",
]
resolver = "3"

[profile.dev]
# Slint can be pretty aggressive with stack allocations, extend stack size to 8MB.
# rustflags = ["-C", "link-args=/STACK:8388608"]
rustflags = ["-C", "link-args=-Wl,--stack,8388608"]

[profile.release]
# Slint can be pretty aggressive with stack allocations, extend stack size to 8MB.
# rustflags = ["-C", "link-args=/STACK:8388608"]
rustflags = ["-C", "link-args=-Wl,--stack,8388608"]

[profile.release-with-debug]
inherits = "release"
debug = true
