[package]
name = "interprocess-shell"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"

[dependencies]
bincode = ">=1.3.3"
interprocess = ">=2.2.2"
log = ">=0.4.26"
serde = ">=1.0.217"
uuid = ">=1.13.1"

[build-dependencies]

