[package]
name = "squalr-engine"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
squalr-engine-api = { path = "../squalr-engine-api" }
squalr-engine-architecture = { path = "../squalr-engine-architecture" }
squalr-engine-common = { path = "../squalr-engine-common" }
squalr-engine-debuggers = { path = "../squalr-engine-debuggers" }
squalr-engine-memory = { path = "../squalr-engine-memory" }
squalr-engine-processes = { path = "../squalr-engine-processes" }
squalr-engine-projects = { path = "../squalr-engine-projects" }
squalr-engine-scanning = { path = "../squalr-engine-scanning" }
squalr-engine-scripting = { path = "../squalr-engine-scripting" }
bincode = "=1.3.3"
crossbeam-channel = ">=0.5.15"
dashmap = ">=6.1.0"
interprocess = ">=2.2.2"
log = ">=0.4.26"
opener = "0.7.2"
serde = { version = ">=1.0.219", features = ["derive"] }
serde_json = ">=1.0.140"
structopt = ">=0.3.26"
sysinfo = ">=0.30"
uuid = { version = "1.15.1", features = ["v4"] }

[build-dependencies]

