[package]
name = "squalr-engine"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
interprocess-shell = { path = "../interprocess-shell" }
squalr-engine-api = { path = "../squalr-engine-api" }
squalr-engine-architecture = { path = "../squalr-engine-architecture" }
squalr-engine-common = { path = "../squalr-engine-common" }
squalr-engine-debuggers = { path = "../squalr-engine-debuggers" }
squalr-engine-memory = { path = "../squalr-engine-memory" }
squalr-engine-processes = { path = "../squalr-engine-processes" }
squalr-engine-scanning = { path = "../squalr-engine-scanning" }
squalr-engine-scripting = { path = "../squalr-engine-scripting" }
crossbeam-channel = ">=0.5.14"
log = ">=0.4.26"
serde = ">=1.0.218"
structopt = ">=0.3.26"
sysinfo = ">=0.30"

[build-dependencies]

