[package]
name = "slint-mvvm"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"

[dependencies]
log = ">=0.4.27"
slint = { version = ">=1.10.0", default-features = false, features = ["accessibility", "compat-1-2", "std"] }

[build-dependencies]

