[package]
name = "olorin-engine-debuggers"
version = "0.1.1"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
olorin-engine-common = { path = "../olorin-engine-common" }
olorin-engine-api = { path = "../olorin-engine-api" }

[build-dependencies]

